/**
 * @author Software Design Group 1
 * ALLEN VAN DIEMAN
 * ANTHONY NDUBUISI JUNIOR JOSEPH
 */

package designsystem;

//import database and formatting libraries 
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class ChangePasswordSystem extends javax.swing.JFrame {

    //instance variables where new infomation will be saved
    String uname;
    String pword;
    String currentPassword;
    String confirmPassword;
    String newPassword;
    
    //database instance variables
    private static final String username = "<database username>";
    private static final String password = "<database password>";
    private static final String database = "jdbc:mysql://<database ip>:3306/<DATABASE>";
    Connection sqlConn = null;
    PreparedStatement pst = null;
    
    //construtor to pass username and password to change password page
    public ChangePasswordSystem(String uname, String pword) {
        initComponents();
                 
        Image img=new ImageIcon(this.getClass().getResource("/CPUT icon.jpg")).getImage();
        this.setIconImage(img);
        
        this.uname = uname;
        this.pword = pword;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBUpdatePassword = new javax.swing.JButton();
        jPFNewPassword = new javax.swing.JPasswordField();
        jPFCurrentPassword = new javax.swing.JPasswordField();
        jPFConfirmPassword = new javax.swing.JPasswordField();
        ShowNewPassword = new javax.swing.JRadioButton();
        ShowConfirmPassword = new javax.swing.JRadioButton();
        ShowCurrentPassword = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 2, 36)); // NOI18N
        jLabel1.setText("      Reset Password ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 400, 41));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Current Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 142, 140, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("New Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 213, 140, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 287, -1, -1));

        jBUpdatePassword.setText("Update Password");
        jBUpdatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdatePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jBUpdatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 366, 370, 34));
        getContentPane().add(jPFNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, -1));
        getContentPane().add(jPFCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 165, 257, -1));
        getContentPane().add(jPFConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 312, 257, -1));

        ShowNewPassword.setText("Show Password");
        ShowNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowNewPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ShowNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 241, -1, -1));

        ShowConfirmPassword.setText("Show Password");
        ShowConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowConfirmPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ShowConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 313, 117, -1));

        ShowCurrentPassword.setText("Show Password");
        ShowCurrentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowCurrentPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ShowCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 166, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot 2024-09-29 2220551.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowConfirmPasswordActionPerformed
       if(ShowConfirmPassword.isSelected()){
            jPFConfirmPassword.setEchoChar((char)0);
        }
        else{
            jPFConfirmPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowConfirmPasswordActionPerformed

    private void ShowCurrentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowCurrentPasswordActionPerformed
       if(ShowCurrentPassword.isSelected()){
            jPFCurrentPassword.setEchoChar((char)0);
        }
        else{
            jPFCurrentPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowCurrentPasswordActionPerformed

    private void ShowNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowNewPasswordActionPerformed
         if(ShowNewPassword.isSelected()){
            jPFNewPassword.setEchoChar((char)0);
        }
        else{
            jPFNewPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowNewPasswordActionPerformed

    private void jBUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdatePasswordActionPerformed
     currentPassword = new String(jPFCurrentPassword.getPassword());
     confirmPassword = new String(jPFConfirmPassword.getPassword());
     newPassword = new String(jPFNewPassword.getPassword());

    // check password match once match update loginData page
    if(currentPassword.equals(pword))
    {
        if(newPassword.equals(confirmPassword))
        {
            try
	{
		Class.forName("com.mysql.cj.jdbc.Driver");
		sqlConn = DriverManager.getConnection(database,username,password);
		pst = sqlConn.prepareStatement("UPDATE loginData set password = ? WHERE username = ?");
                pst.setString(1, newPassword);
                pst.setString(2, uname);
                pst.executeUpdate();
                Login lg=new Login();
                lg.setLocationRelativeTo(null);
                lg.setVisible(true);
                this.dispose();
                
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,"Passwords dont match!!","Error",JOptionPane.ERROR_MESSAGE );
            jPFConfirmPassword.setText("");
            jPFNewPassword.setText("");
        }    
    }
    else
    {
        javax.swing.JOptionPane.showMessageDialog(this,"Incorrect Password!","Error",JOptionPane.ERROR_MESSAGE );
        jPFCurrentPassword.setText("");
    }
  
    }//GEN-LAST:event_jBUpdatePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new ChangePasswordSystem().setVisible(true);  //comeback
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ShowConfirmPassword;
    private javax.swing.JRadioButton ShowCurrentPassword;
    private javax.swing.JRadioButton ShowNewPassword;
    private javax.swing.JButton jBUpdatePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPFConfirmPassword;
    private javax.swing.JPasswordField jPFCurrentPassword;
    private javax.swing.JPasswordField jPFNewPassword;
    // End of variables declaration//GEN-END:variables
}
