
package designsystem;

//import database and formatting libraries 
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;

public class SubjectMarks extends javax.swing.JFrame {

    //Database instance variables
    private static final String username = "<database username>";
    private static final String password = "<database password>";
    private static final String database = "jdbc:mysql://<database ip>:3306/<DATABASE>";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int SelectedRows = -1;
    
    String studentNr;
    
    // database update function (same as login)
    public final void upDateDB(){
	try
	{
		Class.forName("com.mysql.cj.jdbc.Driver");
		sqlConn = DriverManager.getConnection(database,username,password);
		pst = sqlConn.prepareStatement("select * from marks where studentNr = ?");
                pst.setString(1,studentNr);
		rs = pst.executeQuery();

		DefaultTableModel RecordTable = (DefaultTableModel)jTMarks.getModel();
		RecordTable.setRowCount(0);

                rs.next();
                for(int i = 1 ; i < 3 ; i++)
		{
			Vector columnData = new Vector();
                        columnData.add(rs.getString("M" + i)); //depends on colum count
			columnData.add(rs.getString("P" + i)); 
			columnData.add(rs.getString("S" + i)); 
                        columnData.add(rs.getString("E" + i)); 
                        RecordTable.addRow(columnData);
		}
	
	}
	catch(ClassNotFoundException | SQLException ex)
	{
		JOptionPane.showMessageDialog(null, ex);
	}
}
    
    //defualt construtor to load name and student number to page
    public SubjectMarks(String studentNr , String studentName) {
        initComponents();
        this.studentNr = studentNr;
        jLname.setText(studentName + " " + studentNr);
        Image img=new ImageIcon(this.getClass().getResource("/CPUT icon.jpg")).getImage();
        this.setIconImage(img);
        upDateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTMarks = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jBBack = new javax.swing.JButton();
        jTFSoftwareDesign = new javax.swing.JTextField();
        jTFPhysics = new javax.swing.JTextField();
        jTFElectronics = new javax.swing.JTextField();
        jTFMath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTMarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mathematics", "Physics", "Software Design", "Electronics"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTMarks.setAutoscrolls(false);
        jTMarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMarksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTMarks);
        if (jTMarks.getColumnModel().getColumnCount() > 0) {
            jTMarks.getColumnModel().getColumn(0).setResizable(false);
            jTMarks.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 400, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel2.setText("Subject Marks");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 230, 50));

        jBBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBBack.setText("<<Back");
        jBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFSoftwareDesign.setPreferredSize(new java.awt.Dimension(66, 22));
        getContentPane().add(jTFSoftwareDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 70, -1));

        jTFPhysics.setPreferredSize(new java.awt.Dimension(66, 22));
        getContentPane().add(jTFPhysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 70, -1));

        jTFElectronics.setPreferredSize(new java.awt.Dimension(66, 22));
        getContentPane().add(jTFElectronics, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 70, -1));

        jTFMath.setPreferredSize(new java.awt.Dimension(66, 22));
        getContentPane().add(jTFMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 70, -1));

        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Semester 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Electronics");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLname.setText("Name and Surname Student Number");
        getContentPane().add(jLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Semester 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Mathematics");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Physics");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText("Software Design");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot 2024-09-29 2220551.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackActionPerformed
        //always return as admin
        StudentManagementSystem ds=new StudentManagementSystem(0);
        ds.setLocationRelativeTo(null);
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBBackActionPerformed

    private void jTMarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMarksMouseClicked
        //Load selected row to textboxes
        DefaultTableModel RecordTable = (DefaultTableModel)jTMarks.getModel();
        SelectedRows = jTMarks.getSelectedRow();       
        jTFMath.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        jTFPhysics.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        jTFSoftwareDesign.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        jTFElectronics.setText(RecordTable.getValueAt(SelectedRows, 3).toString());         
    }//GEN-LAST:event_jTMarksMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Update button, load marks to variables
        int workingRow = SelectedRows + 1;
        String M = jTFMath.getText();
        String P = jTFPhysics.getText();
        String S = jTFSoftwareDesign.getText();
        String E = jTFElectronics.getText();
        
        //make sure a row is selected then update database via MySQL command
        if(SelectedRows == -1)
        {
            JOptionPane.showMessageDialog(this, "Please select a row to edit");
        }
        else
        {
            try
	{
		Class.forName("com.mysql.cj.jdbc.Driver");
		sqlConn = DriverManager.getConnection(database,username,password);
		pst = sqlConn.prepareStatement("UPDATE marks SET M? = ?, P? = ?, S? = ?, E? = ? where studentNr = ?");
                pst.setInt(1,workingRow);
                pst.setString(2, M);
                pst.setInt(3,workingRow);
                pst.setString(4, P);
                pst.setInt(5,workingRow);
                pst.setString(6, S);
                pst.setInt(7,workingRow);
                pst.setString(8, E);
                pst.setString(9, studentNr);
		pst.executeUpdate();
                
                upDateDB();
                JOptionPane.showMessageDialog(this, "Record Updated","Update Complete",JOptionPane.INFORMATION_MESSAGE);
	}
        catch(ClassNotFoundException | SQLException ex)
	{
		JOptionPane.showMessageDialog(null, ex);
	}
            
        }
          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //we dont want to create this page like this
            //new SubjectMarks().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLname;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFElectronics;
    private javax.swing.JTextField jTFMath;
    private javax.swing.JTextField jTFPhysics;
    private javax.swing.JTextField jTFSoftwareDesign;
    private javax.swing.JTable jTMarks;
    // End of variables declaration//GEN-END:variables
}
